export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ALLRECEIPTS_REQUEST = "ALLRECEIPTS_REQUEST";
export const ALLRECEIPTS_SUCCESS = "ALLRECEIPTS_SUCCESS";
export const ALLRECEIPTS_FAIL = "ALLRECEIPTS_FAIL";
export const ALLRECEIPTS_RESET = "ALLRECEIPTS_RESET";

export const ALLPRESCRIPTIONS_REQUEST = "ALLPRESCRIPTIONS_REQUEST";
export const ALLPRESCRIPTIONS_SUCCESS = "ALLPRESCRIPTIONS_SUCCESS";
export const ALLPRESCRIPTIONS_FAIL = "ALLPRESCRIPTIONS_FAIL";
export const ALLPRESCRIPTIONS_RESET = "ALLPRESCRIPTIONS_RESET"

export const ALLPATIENTS_REQUEST = "ALLPATIENTS_REQUEST";
export const ALLPATIENTS_SUCCESS = "ALLPATIENTS_SUCCESS";
export const ALLPATIENTS_FAIL = "ALLPATIENTS_FAIL";
export const ALLPATIENTS_RESET = "ALLPATIENTS_RESET"

export const ALLDOCTORS_REQUEST = "ALLDOCTORS_REQUEST";
export const ALLDOCTORS_SUCCESS = "ALLDOCTORS_SUCCESS";
export const ALLDOCTORS_FAIL = "ALLDOCTORS_FAIL";
export const ALLDOCTORS_RESET = "ALLDOCTORS_RESET";

export const DOCTORADMIN_DETAILS_REQUEST = "DOCTORADMIN_DETAILS_REQUEST";
export const DOCTORADMIN_DETAILS_SUCCESS = "DOCTORADMIN_DETAILS_SUCCESS";
export const DOCTORADMIN_DETAILS_FAIL = "DOCTORADMIN_DETAILS_FAIL";

export const PATIENTADMIN_DETAILS_REQUEST = "PATIENTADMIN_DETAILS_REQUEST";
export const PATIENTADMIN_DETAILS_SUCCESS = "PATIENTADMIN_DETAILS_SUCCESS";
export const PATIENTADMIN_DETAILS_FAIL = "PATIENTADMIN_DETAILS_FAIL";

export const DOCTOR_DELETE_REQUEST = "DOCTOR_DELETE_REQUEST";
export const DOCTOR_DELETE_SUCCESS = "DOCTOR_DELETE_SUCCESS";
export const DOCTOR_DELETE_FAIL = "DOCTOR_DELETE_FAIL";
export const DOCTOR_DELETE_RESET = "DOCTOR_DELETE_RESET";

export const PATIENT_DELETE_REQUEST = "PATIENT_DELETE_REQUEST";
export const PATIENT_DELETE_SUCCESS = "PATIENT_DELETE_SUCCESS";
export const PATIENT_DELETE_FAIL = "PATIENT_DELETE_FAIL";
export const PATIENT_DELETE_RESET = "PATIENT_DELETE_RESET";

export const DOCTOR_VERIFY_REQUEST = "DOCTOR_VERIFY_REQUEST";
export const DOCTOR_VERIFY_SUCCESS = "DOCTOR_VERIFY_SUCCESS";
export const DOCTOR_VERIFY_FAIL = "DOCTOR_VERIFY_FAIL";
export const DOCTOR_VERIFY_RESET = "DOCTOR_VERIFY_RESET";

export const DOCTOR_REVIEWS_REQUEST = "DOCTOR_REVIEWS_REQUEST";
export const DOCTOR_REVIEWS_SUCCESS = "DOCTOR_REVIEWS_SUCCESS";
export const DOCTOR_REVIEWS_FAIL = "DOCTOR_REVIEWS_FAIL";
export const DOCTOR_REVIEWS_RESET = "DOCTOR_REVIEWS_RESET";

export const ADMIN_APPROVE_REQUEST = "ADMIN_APPROVE_REQUEST";
export const ADMIN_APPROVE_SUCCESS = "ADMIN_APPROVE_SUCCESS";
export const ADMIN_APPROVE_FAIL = "ADMIN_APPROVE_FAIL";
export const ADMIN_APPROVE_RESET = "ADMIN_APPROVE_RESET";

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";
export const REVIEW_DELETE_RESET = "REVIEW_DELETE_RESET";

export const GENERATE_PROMOCODE_REQUEST = "GENERATE_PROMOCODE_REQUEST";
export const GENERATE_PROMOCODE_SUCCESS = "GENERATE_PROMOCODE_SUCCESS";
export const GENERATE_PROMOCODE_FAIL = "GENERATE_PROMOCODE_FAIL";
export const GENERATE_PROMOCODE_RESET = "GENERATE_PROMOCODE_RESET";

export const ALLPROMOCODES_REQUEST = "ALLPROMOCODES_REQUEST";
export const ALLPROMOCODES_SUCCESS = "ALLPROMOCODES_SUCCESS";
export const ALLPROMOCODES_FAIL = "ALLPROMOCODES_FAIL";
export const ALLPROMOCODES_RESET = "ALLPROMOCODES_RESET";

export const DELETE_PROMOCODE_REQUEST = "DELETE_PROMOCODE_REQUEST";
export const DELETE_PROMOCODE_SUCCESS = "DELETE_PROMOCODE_SUCCESS";
export const DELETE_PROMOCODE_FAIL = "DELETE_PROMOCODE_FAIL";
export const DELETE_PROMOCODE_RESET = "DELETE_PROMOCODE_RESET";

export const SUMMARY_LIST_REQUEST = "SUMMARY_LIST_REQUEST";
export const SUMMARY_LIST_SUCCESS = "SUMMARY_LIST_SUCCESS";
export const SUMMARY_LIST_FAIL = "SUMMARY_LIST_FAIL";
export const SUMMARY_LIST_RESET = "SUMMARY_LIST_RESET";

export const REFERRAL_LIST_REQUEST = "REFERRAL_LIST_REQUEST";
export const REFERRAL_LIST_SUCCESS = "REFERRAL_LIST_SUCCESS";
export const REFERRAL_LIST_FAIL = "REFERRAL_LIST_FAIL";
export const REFERRAL_LIST_RESET = "REFERRAL_LIST_RESET";

export const MESSAGE_ADMIN_REQUEST = "MESSAGE_ADMIN_REQUEST";
export const MESSAGE_ADMIN_SUCCESS = "MESSAGE_ADMIN_SUCCESS";
export const MESSAGE_ADMIN_FAIL = "MESSAGE_ADMIN_FAIL";
export const MESSAGE_ADMIN_RESET = "MESSAGE_ADMIN_RESET";

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL";
export const SEND_EMAIL_RESET = "SEND_EMAIL_RESET";

export const SEND_SMS_REQUEST = "SEND_SMS_REQUEST";
export const SEND_SMS_SUCCESS = "SEND_SMS_SUCCESS";
export const SEND_SMS_FAIL = "SEND_SMS_FAIL";
export const SEND_SMS_RESET = "SEND_SMS_RESET";

export const CLEAR_ERRORS = 'CLEAR_ERRORS'