export const DOCTOR_LOGIN_REQUEST = "DOCTOR_LOGIN_REQUEST";
export const DOCTOR_LOGIN_SUCCESS = "DOCTOR_LOGIN_SUCCESS";
export const DOCTOR_LOGIN_FAIL = "DOCTOR_LOGIN_FAIL";
export const DOCTOR_LOGOUT = "DOCTOR_LOGOUT";

export const DOCTOR_REGISTER_REQUEST = "DOCTOR_REGISTER_REQUEST";
export const DOCTOR_REGISTER_SUCCESS = "DOCTOR_REGISTER_SUCCESS";
export const DOCTOR_REGISTER_FAIL = "DOCTOR_REGISTER_FAIL";
export const DOCTOR_REGISTER_RESET = "DOCTOR_REGISTER_RESET";

export const DOCTOR_CONFIRM_REGISTER_REQUEST =
  "DOCTOR_CONFIRM_REGISTER_REQUEST";
export const DOCTOR_CONFIRM_REGISTER_SUCCESS =
  "DOCTOR_CONFIRM_REGISTER_SUCCESS";
export const DOCTOR_CONFIRM_REGISTER_FAIL = "DOCTOR_CONFIRM_REGISTER_FAIL";
export const DOCTOR_CONFIRM_REGISTER_RESET = "DOCTOR_CONFIRM_REGISTER_RESET";

export const RESENDMAIL_REQUEST = "RESENDMAIL_REQUEST";
export const RESENDMAIL_SUCCESS = "RESENDMAIL_SUCCESS";
export const RESENDMAIL_FAIL = "RESENDMAIL_FAIL";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";

export const DOCTOR_PROFILE_REQUEST = "DOCTOR_PROFILE_REQUEST";
export const DOCTOR_PROFILE_SUCCESS = "DOCTOR_PROFILE_SUCCESS";
export const DOCTOR_PROFILE_FAIL = "DOCTOR_PROFILE_FAIL";

export const DOCTOR_UPDATE_PROFILE_REQUEST = "DOCTOR_UPDATE_PROFILE_REQUEST";
export const DOCTOR_UPDATE_PROFILE_SUCCESS = "DOCTOR_UPDATE_PROFILE_SUCCESS";
export const DOCTOR_UPDATE_PROFILE_FAIL = "DOCTOR_UPDATE_PROFILE_FAIL";
export const DOCTOR_UPDATE_PROFILE_RESET = "DOCTOR_UPDATE_PROFILE_RESET";

export const DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST";
export const DOCTOR_LIST_SUCCESS = "DOCTOR_LIST_SUCCESS";
export const DOCTOR_LIST_FAIL = "DOCTOR_LIST_FAIL";
export const DOCTOR_LIST_RESET = "DOCTOR_LIST_RESET";

export const DOCTOR_DELETE_REQUEST = "DOCTOR_DELETE_REQUEST";
export const DOCTOR_DELETE_SUCCESS = "DOCTOR_DELETE_SUCCESS";
export const DOCTOR_DELETE_FAIL = "DOCTOR_DELETE_FAIL";

export const DOCTOR_UPDATE_REQUEST = "DOCTOR_UPDATE_REQUEST";
export const DOCTOR_UPDATE_SUCCESS = "DOCTOR_UPDATE_SUCCESS";
export const DOCTOR_UPDATE_FAIL = "DOCTOR_UPDATE_FAIL";
export const DOCTOR_UPDATE_RESET = "DOCTOR_UPDATE_RESET";

export const DOCTORPHONEVERIFY_SUCCESS = "DOCTORPHONEVERIFY_SUCCESS";
export const DOCTORPHONEVERIFY_FAIL = "DOCTORPHONEVERIFY_FAIL";

export const DOCTORPHONECODEVERIFY_REQUEST = "DOCTORPHONECODEVERIFY_REQUEST";
export const DOCTORPHONECODEVERIFY_SUCCESS = "DOCTORPHONECODEVERIFY_SUCCESS";
export const DOCTORPHONECODEVERIFY_FAIL = "DOCTORPHONECODEVERIFY_FAIL";
export const DOCTORPHONECODEVERIFY_RESET = "DOCTORPHONECODEVERIFY_RESET";

export const NEWPRESCRIPTION_REQUEST = "NEWPRESCRIPTION_REQUEST";
export const NEWPRESCRIPTION_SUCCESS = "NEWPRESCRIPTION_SUCCESS";
export const NEWPRESCRIPTION_FAIL = "NEWPRESCRIPTION_FAIL";
export const NEWPRESCRIPTION_RESET = "NEWPRESCRIPTION_RESET";

export const DOCTORPRESCRIPTION_LIST_REQUEST =
  "DOCTORPRESCRIPTION_LIST_REQUEST";
export const DOCTORPRESCRIPTION_LIST_SUCCESS =
  "DOCTORPRESCRIPTION_LIST_SUCCESS";
export const DOCTORPRESCRIPTION_LIST_FAIL = "DOCTORPRESCRIPTION_LIST_FAIL";
export const DOCTORPRESCRIPTION_LIST_RESET = "DOCTORPRESCRIPTION_LIST_RESET";

export const UPDATEPRESCRIPTION_DETAIL_REQUEST = "UPDATEPRESCRIPTION_DETAIL_REQUEST";
export const UPDATEPRESCRIPTION_DETAIL_SUCCESS = "UPDATEPRESCRIPTION_DETAIL_SUCCESS";
export const UPDATEPRESCRIPTION_DETAIL_FAIL = "UPDATEPRESCRIPTION_DETAIL_FAIL";
export const UPDATEPRESCRIPTION_DETAIL_RESET = "UPDATEPRESCRIPTION_DETAIL_RESET";


export const DOCTOR_PASSWORDRESET_REQUEST = "DOCTOR_PASSWORDRESET_REQUEST";
export const DOCTOR_PASSWORDRESET_SUCCESS = "DOCTOR_PASSWORDRESET_SUCCESS";
export const DOCTOR_PASSWORDRESET_FAIL = "DOCTOR_PASSWORDRESET_FAIL";
export const DOCTOR_PASSWORDRESET_RESET = "DOCTOR_PASSWORDRESET_RESET";

export const DOCTOR_NEWPASSWORD_REQUEST = "DOCTOR_NEWPASSWORD_REQUEST";
export const DOCTOR_NEWPASSWORD_SUCCESS = "DOCTOR_NEWPASSWORD_SUCCESS";
export const DOCTOR_NEWPASSWORD_FAIL = "DOCTOR_NEWPASSWORD_FAIL";
export const DOCTOR_NEWPASSWORD_RESET = "DOCTOR_NEWPASSWORD_RESET";

export const CREATECONSULTATION_SUMMARY_REQUEST =
  "CREATECONSULTATION_SUMMARY_REQUEST";
export const CREATECONSULTATION_SUMMARY_SUCCESS =
  "CREATECONSULTATION_SUMMARY_SUCCESS";
export const CREATECONSULTATION_SUMMARY_FAIL =
  "CREATECONSULTATION_SUMMARY_FAIL";
export const CREATECONSULTATION_SUMMARY_RESET =
  "CREATECONSULTATION_SUMMARY_RESET";

export const SUMMARY_LIST_REQUEST = "SUMMARY_LIST_REQUEST";
export const SUMMARY_LIST_SUCCESS = "SUMMARY_LIST_SUCCESS";
export const SUMMARY_LIST_FAIL = "SUMMARY_LIST_FAIL";
export const SUMMARY_LIST_RESET = "SUMMARY_LIST_RESET";

export const SUMMARY_DETAIL_REQUEST = "SUMMARY_DETAIL_REQUEST";
export const SUMMARY_DETAIL_SUCCESS = "SUMMARY_DETAIL_SUCCESS";
export const SUMMARY_DETAIL_FAIL = "SUMMARY_DETAIL_FAIL";
export const SUMMARY_DETAIL_RESET = "SUMMARY_DETAIL_RESET";

export const UPDATESUMMARY_DETAIL_REQUEST = "UPDATESUMMARY_DETAIL_REQUEST";
export const UPDATESUMMARY_DETAIL_SUCCESS = "UPDATESUMMARY_DETAIL_SUCCESS";
export const UPDATESUMMARY_DETAIL_FAIL = "UPDATESUMMARY_DETAIL_FAIL";
export const UPDATESUMMARY_DETAIL_RESET = "UPDATESUMMARY_DETAIL_RESET";

export const SUMMARY_PERCHAT_REQUEST = "SUMMARY_PERCHAT_REQUEST";
export const SUMMARY_PERCHAT_SUCCESS = "SUMMARY_PERCHAT_SUCCESS";
export const SUMMARY_PERCHAT_FAIL = "SUMMARY_PERCHAT_FAIL";
export const SUMMARY_PERCHAT_RESET = "SUMMARY_PERCHAT_RESET";

export const CREATECONSULTATION_REFERRAL_REQUEST =
  " CREATECONSULTATION_REFERRAL_REQUEST";
export const CREATECONSULTATION_REFERRAL_SUCCESS =
  " CREATECONSULTATION_REFERRAL_SUCCESS";
export const CREATECONSULTATION_REFERRAL_FAIL =
  " CREATECONSULTATION_REFERRAL_FAIL";
export const CREATECONSULTATION_REFERRAL_RESET =
  " CREATECONSULTATION_REFERRAL_RESET";

export const REFERRAL_LIST_REQUEST = " REFERRAL_LIST_REQUEST";
export const REFERRAL_LIST_SUCCESS = " REFERRAL_LIST_SUCCESS";
export const REFERRAL_LIST_FAIL = " REFERRAL_LIST_FAIL";
export const REFERRAL_LIST_RESET = " REFERRAL_LIST_RESET";

export const REFERRAL_DETAIL_REQUEST = " REFERRAL_DETAIL_REQUEST";
export const REFERRAL_DETAIL_SUCCESS = " REFERRAL_DETAIL_SUCCESS";
export const REFERRAL_DETAIL_FAIL = " REFERRAL_DETAIL_FAIL";
export const REFERRAL_DETAIL_RESET = " REFERRAL_DETAIL_RESET";

export const UPDATEREFERRAL_DETAIL_REQUEST = "UPDATEREFERRAL_DETAIL_REQUEST";
export const UPDATEREFERRAL_DETAIL_SUCCESS = "UPDATEREFERRAL_DETAIL_SUCCESS";
export const UPDATEREFERRAL_DETAIL_FAIL = "UPDATEREFERRAL_DETAIL_FAIL";
export const UPDATEREFERRAL_DETAIL_RESET = "UPDATEREFERRAL_DETAIL_RESET";

export const ADD_ACCT_REQUEST = " ADD_ACCT_REQUEST";
export const ADD_ACCT_SUCCESS = " ADD_ACCT_SUCCESS";
export const ADD_ACCT_FAIL = " ADD_ACCT_FAIL";
export const ADD_ACCT_RESET = " ADD_ACCT_RESET";

export const GET_ACCTLIST_REQUEST = " GET_ACCTLIST_REQUEST";
export const GET_ACCTLIST_SUCCESS = " GET_ACCTLIST_SUCCESS";
export const GET_ACCTLIST_FAIL = " GET_ACCTLIST_FAIL";
export const GET_ACCTLIST_RESET = " GET_ACCTLIST_RESET";

export const ACCTLIST_OPENACCESS_REQUEST = " ACCTLIST_OPENACCESS_REQUEST";
export const ACCTLIST_OPENACCESS_SUCCESS = " ACCTLIST_OPENACCESS_SUCCESS";
export const ACCTLIST_OPENACCESS_FAIL = " ACCTLIST_OPENACCESS_FAIL";
export const ACCTLIST_OPENACCESS_RESET = " ACCTLIST_OPENACCESS_RESET";

export const GET_ACCTDETAIL_REQUEST = " GET_ACCTDETAIL_REQUEST";
export const GET_ACCTDETAIL_SUCCESS = " GET_ACCTDETAIL_SUCCESS";
export const GET_ACCTDETAIL_FAIL = " GET_ACCTDETAIL_FAIL";
export const GET_ACCTDETAIL_RESET = " GET_ACCTDETAIL_RESET";

export const UPDATE_ACCTDETAIL_REQUEST = " UPDATE_ACCTDETAIL_REQUEST";
export const UPDATE_ACCTDETAIL_SUCCESS = " UPDATE_ACCTDETAIL_SUCCESS";
export const UPDATE_ACCTDETAIL_FAIL = " UPDATE_ACCTDETAIL_FAIL";
export const UPDATE_ACCTDETAIL_RESET = " UPDATE_ACCTDETAIL_RESET";

export const DELETE_ACCT_REQUEST = " DELETE_ACCT_REQUEST";
export const DELETE_ACCT_SUCCESS = " DELETE_ACCT_SUCCESS";
export const DELETE_ACCT_FAIL = " DELETE_ACCT_FAIL";
export const DELETE_ACCT_RESET = " DELETE_ACCT_RESET";

export const CHANGE_PASSWORD_REQUEST = " CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = " CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = " CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_RESET = " CHANGE_PASSWORD_RESET";

export const UPDATE_DOCUMENT_REQUEST = " UPDATE_DOCUMENT_REQUEST";
export const UPDATE_DOCUMENT_SUCCESS = " UPDATE_DOCUMENT_SUCCESS";
export const UPDATE_DOCUMENT_FAIL = " UPDATE_DOCUMENT_FAIL";
export const UPDATE_DOCUMENT_RESET = " UPDATE_DOCUMENT_RESET";
