export const INITIATE_ADD_DOCTORREQUEST = "INITIATE_ADD_DOCTORREQUEST";
export const INITIATE_ADD_DOCTORSUCCESS = "INITIATE_ADD_DOCTORSUCCESS";
export const INITIATE_ADD_DOCTORFAIL = "INITIATE_ADD_DOCTORFAIL";
export const INITIATE_ADD_COMPLAINT = "INITIATE_ADD_COMPLAINT";
export const INITIATE_SAVE_PAYMENT_METHOD = "INITIATE_SAVE_PAYMENT_METHOD";
export const INITIATE_CLEAR_ITEMS = "INITIATE_CLEAR_ITEMS"; 