export const CONSULTATIONORDER_CREATE_REQUEST = "CONSULTATIONORDER_CREATE_REQUEST";
export const CONSULTATIONORDER_CREATE_SUCCESS = "CONSULTATIONORDER_CREATE_SUCCESS";
export const CONSULTATIONORDER_CREATE_FAIL = "CONSULTATIONORDER_CREATE_FAIL";
export const CONSULTATIONORDER_CREATE_RESET = "CONSULTATIONORDER_CREATE_RESET";

export const CONSULTATIONORDER_DETAILS_REQUEST = "CONSULTATIONORDER_DETAILS_REQUEST";
export const CONSULTATIONORDER_DETAILS_SUCCESS = "CONSULTATIONORDER_DETAILS_SUCCESS";
export const CONSULTATIONORDER_DETAILS_FAIL = "CONSULTATIONORDER_DETAILS_FAIL";

export const CONSULTATIONORDER_PAY_REQUEST = "CONSULTATIONORDER_PAY_REQUEST";
export const CONSULTATIONORDER_PAY_SUCCESS = "CONSULTATIONORDER_PAY_SUCCESS";
export const CONSULTATIONORDER_PAY_FAIL = "CONSULTATIONORDER_PAY_FAIL";
export const CONSULTATIONORDER_PAY_RESET = "CONSULTATIONORDER_PAY_RESET";

export const CONSULTATIONORDER_LIST_MY_REQUEST = "CONSULTATIONORDER_LIST_MY_REQUEST";
export const CONSULTATIONORDER_LIST_MY_SUCCESS = "CONSULTATIONORDER_LIST_MY_SUCCESS";
export const CONSULTATIONORDER_LIST_MY_FAIL = "CONSULTATIONORDER_LIST_MY_FAIL";
export const CONSULTATIONORDER_LIST_MY_RESET = "CONSULTATIONORDER_LIST_MY_RESET";

export const CONSULTATIONORDER_LIST_REQUEST = "CONSULTATIONORDER_LIST_REQUEST";
export const CONSULTATIONORDER_LIST_SUCCESS = "CONSULTATIONORDER_LIST_SUCCESS";
export const CONSULTATIONORDER_LIST_FAIL = "CONSULTATIONORDER_LIST_FAIL";

export const CONSULTATIONORDER_DELIVER_REQUEST = "CONSULTATIONORDER_DELIVER_REQUEST";
export const CONSULTATIONORDER_DELIVER_SUCCESS = "CONSULTATIONORDER_DELIVER_SUCCESS";
export const CONSULTATIONORDER_DELIVER_FAIL = "CONSULTATIONORDER_DELIVER_FAIL";
export const CONSULTATIONORDER_DELIVER_RESET = "CONSULTATIONORDER_DELIVER_RESET";


export const VERIFY_PAYMENT_REQUEST = "VERIFY_PAYMENT_REQUEST";
export const VERIFY_PAYMENT_SUCCESS = "VERIFY_PAYMENT_SUCCESS";
export const VERIFY_PAYMENT_FAIL = "VERIFY_PAYMENT_FAIL";
export const VERIFY_PAYMENT_RESET = "VERIFY_PAYMENT_RESET";

export const SENDSMS_REQUEST = "SENDSMS_REQUEST";
export const SENDSMS_SUCCESS = "SENDSMS_SUCCESS";
export const SENDSMS_FAIL = "SENDSMS_FAIL";
export const SENDSMS_RESET = "SENDSMS_RESET";


export const LISTDOCTOR_CONSULTATION_REQUEST = "LISTDOCTOR_CONSULTATION_REQUEST";
export const LISTDOCTOR_CONSULTATION_SUCCESS = "LISTDOCTOR_CONSULTATION_SUCCESS";
export const LISTDOCTOR_CONSULTATION_FAIL = "LISTDOCTOR_CONSULTATION_FAIL";
export const LISTDOCTOR_CONSULTATION_RESET = "LISTDOCTOR_CONSULTATION_RESET";

export const LISTALL_CONSULTATION_REQUEST = "LISTALL_CONSULTATION_REQUEST";
export const LISTALL_CONSULTATION_SUCCESS = "LISTALL_CONSULTATION_SUCCESS";
export const LISTALL_CONSULTATION_FAIL = "LISTALL_CONSULTATION_FAIL";
export const LISTALL_CONSULTATION_RESET = "LISTALL_CONSULTATION_RESET";

export const SENDRECEIPT_REQUEST = "SENDRECEIPT_REQUEST";
export const SENDRECEIPT_SUCCESS = "SENDRECEIPT_SUCCESS";
export const SENDRECEIPT_FAIL = "SENDRECEIPT_FAIL";
export const SENDRECEIPT_RESET = "SENDRECEIPT_RESET";

export const DOCTOR_CREATE_REVIEW_REQUEST = "DOCTOR_CREATE_REVIEW_REQUEST";
export const DOCTOR_CREATE_REVIEW_SUCCESS = "DOCTOR_CREATE_REVIEW_SUCCESS";
export const DOCTOR_CREATE_REVIEW_FAIL = "DOCTOR_CREATE_REVIEW_FAIL";
export const DOCTOR_CREATE_REVIEW_RESET = "DOCTOR_CREATE_REVIEW_RESET";

export const DOCTORHASBEENPAID_REQUEST = "DOCTORHASBEENPAID_REQUEST";
export const DOCTORHASBEENPAID_SUCCESS = "DOCTORHASBEENPAID_SUCCESS";
export const DOCTORHASBEENPAID_FAIL = "DOCTORHASBEENPAID_FAIL";
export const DOCTORHASBEENPAID_RESET = "DOCTORHASBEENPAID_RESET";

export const PROMO_CODE_REQUEST = "PROMO_CODE_REQUEST";
export const PROMO_CODE_SUCCESS = "PROMO_CODE_SUCCESS";
export const PROMO_CODE_FAIL = "PROMO_CODE_FAIL";
export const PROMO_CODE_RESET = "PROMO_CODE_RESET";


