export const PATIENT_LOGIN_REQUEST = "PATIENT_LOGIN_REQUEST";
export const PATIENT_LOGIN_SUCCESS = "PATIENT_LOGIN_SUCCESS";
export const PATIENT_MAILNOT_VERIFIED = "PATIENT_MAILNOT_VERIFIED";
export const PATIENT_LOGIN_FAIL = "PATIENT_LOGIN_FAIL";
export const PATIENT_LOGOUT = "PATIENT_LOGOUT";

export const PATIENT_REGISTER_REQUEST = "PATIENT_REGISTER_REQUEST";
export const PATIENT_REGISTER_SUCCESS = "PATIENT_REGISTER_SUCCESS";
export const PATIENT_REGISTER_FAIL = "PATIENT_REGISTER_FAIL";
export const PATIENT_REGISTER_RESET = "PATIENT_REGISTER_RESET";

export const RESENDMAIL_REQUEST = "RESENDMAIL_REQUEST";
export const RESENDMAIL_SUCCESS = "RESENDMAIL_SUCCESS";
export const RESENDMAIL_FAIL = "RESENDMAIL_FAIL";

export const PATIENT_DETAILS_REQUEST = "PATIENT_DETAILS_REQUEST";
export const PATIENT_DETAILS_SUCCESS = "PATIENT_DETAILS_SUCCESS";
export const PATIENT_DETAILS_FAIL = "PATIENT_DETAILS_FAIL";

export const PATIENTPHONEVERIFY_SUCCESS = "PATIENTPHONEVERIFY_SUCCESS";
export const PATIENTPHONEVERIFY_FAIL = "PATIENTPHONEVERIFY_FAIL";

export const PATIENTPHONECODEVERIFY_REQUEST = "PATIENTPHONECODEVERIFY_REQUEST";
export const PATIENTPHONECODEVERIFY_SUCCESS = "PATIENTPHONECODEVERIFY_SUCCESS";
export const PATIENTPHONECODEVERIFY_FAIL = "PATIENTPHONECODEVERIFY_FAIL";
export const PATIENTPHONECODEVERIFY_RESET = "PATIENTPHONECODEVERIFY_RESET";

export const PATIENT_UPDATE_PROFILE_REQUEST = "PATIENT_UPDATE_PROFILE_REQUEST";
export const PATIENT_UPDATE_PROFILE_SUCCESS = "PATIENT_UPDATE_PROFILE_SUCCESS";
export const PATIENT_UPDATE_PROFILE_FAIL = "PATIENT_UPDATE_PROFILE_FAIL";
export const PATIENT_UPDATE_PROFILE_RESET = "PATIENT_UPDATE_PROFILE_RESET";

export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_FAIL = "PATIENT_LIST_FAIL";
export const PATIENT_LIST_RESET = "PATIENT_LIST_RESET";

export const PATIENT_DELETE_REQUEST = "PATIENT_DELETE_REQUEST";
export const PATIENT_DELETE_SUCCESS = "PATIENT_DELETE_SUCCESS";
export const PATIENT_DELETE_FAIL = "PATIENT_DELETE_FAIL";

export const PATIENT_UPDATE_REQUEST = "PATIENT_UPDATE_REQUEST";
export const PATIENT_UPDATE_SUCCESS = "PATIENT_UPDATE_SUCCESS";
export const PATIENT_UPDATE_FAIL = "PATIENT_UPDATE_FAIL";
export const PATIENT_UPDATE_RESET = "PATIENT_UPDATE_RESET";

export const PATIENTPRESCRIPTION_LIST_REQUEST = "PATIENTPRESCRIPTION_LIST_REQUEST";
export const PATIENTPRESCRIPTION_LIST_SUCCESS = "PATIENTPRESCRIPTION_LIST_SUCCESS";
export const PATIENTPRESCRIPTION_LIST_FAIL = "PATIENTPRESCRIPTION_LIST_FAIL";
export const PATIENTPRESCRIPTION_LIST_RESET = "PATIENTPRESCRIPTION_LIST_RESET";

export const PATIENTRECEIPT_LIST_REQUEST = "PATIENTRECEIPT_LIST_REQUEST";
export const PATIENTRECEIPT_LIST_SUCCESS = "PATIENTRECEIPT_LIST_SUCCESS";
export const PATIENTRECEIPT_LIST_FAIL = "PATIENTRECEIPT_LIST_FAIL";
export const PATIENTRECEIPT_LIST_RESET = "PATIENTRECEIPT_LIST_RESET";

export const RECEIPT_DETAIL_REQUEST = "RECEIPT_DETAIL_REQUEST";
export const RECEIPT_DETAIL_SUCCESS = "RECEIPT_DETAIL_SUCCESS";
export const RECEIPT_DETAIL_FAIL = "RECEIPT_DETAIL_FAIL";
export const RECEIPT_DETAIL_RESET = "RECEIPT_DETAIL_RESET";

export const PRESCRIPTION_DETAIL_REQUEST = "PRESCRIPTION_DETAIL_REQUEST";
export const PRESCRIPTION_DETAIL_SUCCESS = "PRESCRIPTION_DETAIL_SUCCESS";
export const PRESCRIPTION_DETAIL_FAIL = "PRESCRIPTION_DETAIL_FAIL";
export const PRESCRIPTION_DETAIL_RESET = "PRESCRIPTION_DETAIL_RESET";

export const PATIENT_PASSWORDRESET_REQUEST = "PATIENT_PASSWORDRESET_REQUEST";
export const PATIENT_PASSWORDRESET_SUCCESS = "PATIENT_PASSWORDRESET_SUCCESS";
export const PATIENT_PASSWORDRESET_FAIL = "PATIENT_PASSWORDRESET_FAIL";
export const PATIENT_PASSWORDRESET_RESET = "PATIENT_PASSWORDRESET_RESET";

export const PATIENT_NEWPASSWORD_REQUEST = "PATIENT_NEWPASSWORD_REQUEST";
export const PATIENT_NEWPASSWORD_SUCCESS = "PATIENT_NEWPASSWORD_SUCCESS";
export const PATIENT_NEWPASSWORD_FAIL = "PATIENT_NEWPASSWORD_FAIL";
export const PATIENT_NEWPASSWORD_RESET = "PATIENT_NEWPASSWORD_RESET";

export const PATIENT_CONFIRM_REGISTER_REQUEST = "PATIENT_CONFIRM_REGISTER_REQUEST";
export const PATIENT_CONFIRM_REGISTER_SUCCESS = "PATIENT_CONFIRM_REGISTER_SUCCESS";
export const PATIENT_CONFIRM_REGISTER_FAIL = "PATIENT_CONFIRM_REGISTER_FAIL";

export const REFERRAL_LIST_REQUEST = "REFERRAL_LIST_REQUEST";
export const REFERRAL_LIST_SUCCESS = "REFERRAL_LIST_SUCCESS";
export const REFERRAL_LIST_FAIL = "REFERRAL_LIST_FAIL";
export const REFERRAL_LIST_RESET = "REFERRAL_LIST_RESET";

export const GET_DOCTOR_BY_INVITEID_REQUEST = "GET_DOCTOR_BY_INVITEID_REQUEST";
export const GET_DOCTOR_BY_INVITEID_SUCCESS = "GET_DOCTOR_BY_INVITEID_SUCCESS";
export const GET_DOCTOR_BY_INVITEID_FAIL = "GET_DOCTOR_BY_INVITEID_FAIL";
export const GET_DOCTOR_BY_INVITEID_RESET = "GET_DOCTOR_BY_INVITEID_RESET";

export const SEND_REMINDER_REQUEST = "SEND_REMINDER_REQUEST";
export const SEND_REMINDER_SUCCESS = "SEND_REMINDER_SUCCESS";
export const SEND_REMINDER_FAIL = "SEND_REMINDER_FAIL";
export const SEND_REMINDER_RESET = "SEND_REMINDER_RESET";

export const  CHANGE_PASSWORD_REQUEST = " CHANGE_PASSWORD_REQUEST";
export const  CHANGE_PASSWORD_SUCCESS = " CHANGE_PASSWORD_SUCCESS";
export const  CHANGE_PASSWORD_FAIL = " CHANGE_PASSWORD_FAIL";
export const  CHANGE_PASSWORD_RESET = " CHANGE_PASSWORD_RESET";

export const  UPDATE_DOCUMENT_REQUEST = " UPDATE_DOCUMENT_REQUEST";
export const  UPDATE_DOCUMENT_SUCCESS = " UPDATE_DOCUMENT_SUCCESS";
export const  UPDATE_DOCUMENT_FAIL = " UPDATE_DOCUMENT_FAIL";
export const  UPDATE_DOCUMENT_RESET = " UPDATE_DOCUMENT_RESET";
