export const REG_STEP1_SUCCESS = 'REG_STEP1_SUCCESS';
export const REG_STEP1_FAIL = 'REG_STEP1_FAIL';
export const REG_STEP2 = 'REG_STEP2';
export const REG_STEP3 = 'REG_STEP3';
export const REG_EMAILSTATUS_SUCCESS = 'REG_EMAILSTATUS_SUCCESS';
export const CLEAR_EMAIL_STATUS = 'CLEAR_EMAIL_STATUS';
export const CLEAR_PW_STATUS = 'CLEAR_PW_STATUS';