export const WALLET_BALANCE_REQUEST = 'WALLET_BALANCE_REQUEST';
export const WALLET_BALANCE_SUCCESS = 'WALLET_BALANCE_SUCCESS';
export const WALLET_BALANCE_FAIL = 'WALLET_BALANCE_FAIL';
export const WALLET_BALANCE_RESET = 'WALLET_BALANCE_RESET';

export const FUND_WALLET_REQUEST = 'FUND_WALLET_REQUEST';
export const FUND_WALLET_SUCCESS = 'FUND_WALLET_SUCCESS';
export const FUND_WALLET_FAIL = 'FUND_WALLET_FAIL';
export const FUND_WALLET_RESET = 'FUND_WALLET_RESET';

export const VERIFY_PAYSTACKFUND_REQUEST = 'VERIFY_PAYSTACKFUND_REQUEST';
export const VERIFY_PAYSTACKFUND_SUCCESS = 'VERIFY_PAYSTACKFUND_SUCCESS';
export const VERIFY_PAYSTACKFUND_FAIL = 'VERIFY_PAYSTACKFUND_FAIL';
export const VERIFY_PAYSTACKFUND_RESET = 'VERIFY_PAYSTACKFUND_RESET';

export const WALLET_TRANSACTIONS_REQUEST = 'WALLET_TRANSACTIONS_REQUEST';
export const WALLET_TRANSACTIONS_SUCCESS = 'WALLET_TRANSACTIONS_SUCCESS';
export const WALLET_TRANSACTIONS_FAIL = 'WALLET_TRANSACTIONS_FAIL';
export const WALLET_TRANSACTIONS_RESET = 'WALLET_TRANSACTIONS_RESET';

export const BANK_VERIFY_REQUEST = 'BANK_VERIFY_REQUEST';
export const BANK_VERIFY_SUCCESS = 'BANK_VERIFY_SUCCESS';
export const BANK_VERIFY_FAIL = 'BANK_VERIFY_FAIL';
export const BANK_VERIFY_RESET = 'BANK_VERIFY_RESET';

export const GET_BANKS_REQUEST = 'GET_BANKS_REQUEST';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';
export const GET_BANKS_FAIL = 'GET_BANKS_FAIL';
export const GET_BANKS_RESET = 'GET_BANKS_RESET';

export const CREATE_RECIPIENT_REQUEST = 'CREATE_RECIPIENT_REQUEST';
export const CREATE_RECIPIENT_SUCCESS = 'CREATE_RECIPIENT_SUCCESS';
export const CREATE_RECIPIENT_FAIL = 'CREATE_RECIPIENT_FAIL';
export const CREATE_RECIPIENT_RESET = 'CREATE_RECIPIENT_RESET';